# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 11:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import User


def initial_data(apps, schema_editor):
    try:
        Company = apps.get_model("consumers", "Company")
        Review = apps.get_model("consumers", "Review")

        User.objects.create_superuser(
            'admin',
            email='admin@example.com',
            password='admin')

        company = Company.objects.create(name="Company X")

        for username in ["user1", "user2"]:
            user = User.objects.create_user(
                username,
                email="{}@example.com".format(username),
                password=username)

            review = Review()
            review.rating = 5
            review.title = "Sample Review from {}".format(user.username)
            review.summary = "Review from {}.".format(user.username)
            review.ip_address = "123.123.123.123"
            review.company = company
            review.reviewer_id = user.id
            review.save()

    except Exception as e:
        print(e)
        print("Unable to load initial data.")

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5', b'5')], max_length=2)),
                ('title', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=10000)),
                ('ip_address', models.CharField(max_length=20)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumers.Company')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submission_date'],
            },
        ),
        migrations.RunPython(initial_data),
    ]
